### ISSUE TITLE
Request to merge into main asciidots repo

### ISSUE THREAD

**Issue by aaronjanse** [francois2metz/docker-asciidots#1]
Thanks for making asciidots compatible with Docker.

I referenced your repo from the main asciidots readme in [commit 53029fe](https://github.com/aaronduino/asciidots/commit/53029fe0f3b18f8518dfc27c42f2cd9fb169f206) (I'm assuming that's okay)

May I also merge this repo's Dockerfile into the main asciidots repo?

**Comment by francois2metz** [comment]
HI @aaronduino. I would more than happy to merge this into the main asciidots repo! 

I'll open the PR with a few changes. We also need to setup a new automated build on the Docker Hub.

**Comment by aaronjanse** [comment]
Sounds great!

Once you make the PR (no rush, btw), I think I can manage setting up an automates build on Docker Hub, although I am open to any advice (I am relatively new to docker hub).

Once again, thanks for the contribution

**Comment by francois2metz** [comment]
Thanks, but it was not needed. I'm going to deprecate this repos now.
